### ISSUE TITLE
Bug dans les distribution.json

### ISSUE THREAD

**Issue by AQRRastiq** [Superkooka/Helios#4]
Hey Superkooka,
Je te préviens que le lien pour le distribution.json du launcher Oerthyon (et donc peut-être aussi les autres) ne marche(nt) pas, normalement il peut être vu sur un navigateur internet (par exemple Chrome) sauf que là, quand je rentre le lien du distribution.json, ça me donne ça : Ce site est inaccessible. Impossible de trouver l'adresse IP du serveur de cdn.superkooka.com. Pourrais-tu régler ce bug stp ?

**Comment by Superkooka** [comment]
Oui en effet ils ne sont plus en ligne 😅 Je suis pas chez moi aujourd’hui je m’en occupe demain :)

**Comment by AQRRastiq** [comment]
Ok
